language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-4.8 libcurl4-openssl-dev libgloox-dev libgtest-dev libleveldb-dev
  - cd /usr/src/gtest && sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd $TRAVIS_BUILD_DIR
make
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make
  - ./lemongrab --test

os:
  - linux
