sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull loonygnoll/lemongrab-build-gentoo
  - gem install coveralls-lcov

script:
  - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -e
    TRAVIS='${TRAVIS}' -e
    TRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -e
    TRAVIS_BRANCH='${TRAVIS_BRANCH}' -e
    COVERALLS_REPO_TOKEN='${COVERALLS_REPO_TOKEN}' -u
    $(id -u):$(id -g) --entrypoint=$TRAVIS_BUILD_DIR/build-in-docker.sh
    loonygnoll/lemongrab-build-gentoo
  - coveralls-lcov --repo-token "${COVERALLS_REPO_TOKEN}" build/coverage.clean.info

os:
  - linux
