language: cpp
sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull loonygnoll/ubuntu-lemongrab-build

script:
  - docker run -v $TRAVIS_BUILD_DIR:/root/ -e COVERALLS_REPO_TOKEN='${COVERALLS_REPO_TOKEN}' loonygnoll/ubuntu-lemongrab-build

os:
  - linux
