language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
          - lcov
          - libcurl4-openssl-dev
          - libgloox-dev
          - libgtest-dev
          - libgoogle-glog-dev
          - libleveldb-dev
          - libevent-dev
          - libboost-locale-dev
    env: CXX="g++-4.9"

before_install:
  - bash travis/install_cmake.sh
  - bash travis/install_jsoncpp.sh
  - bash travis/install_cpr.sh

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DBUILD_COVER=ON
  - make
  - cp -R ../test test
  - mkdir db
  - ./lemongrab --test
  - lcov -c -d . -o coverage.info
  - lcov --remove coverage.info "/usr*" -o coverage.clean.info
  - coveralls-lcov --repo-token "${COVERALLS_REPO_TOKEN}" coverage.clean.info

os:
  - linux
