language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-4.8 libcurl4-openssl-dev libgloox-dev libgtest0 libgtest-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./lemongrab --test

os:
  - linux
